<?php

namespace TournamentBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TeamsRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TeamsRepository extends DocumentRepository
{
    public function getStandings(string $tournamentId)
    {
        return $this->createQueryBuilder()
            ->field('tournamentId')->equals($tournamentId)
            ->sort('battlePoints', -1)
            ->sort('matchPoints', -1)
            ->getQuery()
            ->execute();
    }
}
